/*
 * jQuery Joyride Plugin 1.0.2
 * www.ZURB.com/playground
 * Copyright 2011, ZURB
 * Free to use under the MIT license.
 * http://www.opensource.org/licenses/mit-license.php
*/
(function(b){b.fn.joyride=function(k){var a={tipLocation:"bottom",scrollSpeed:300,timer:0,startTimerOnClick:!1,nextButton:!0,tipAnimation:"pop",tipAnimationFadeSpeed:300,cookieMonster:!1,cookieName:"JoyRide",cookieDomain:!1,tipContainer:"body",inline:!1,tipContent:"#joyRideTipContent",postRideCallback:b.noop,postStepCallback:b.noop},k=b.extend(a,k);return this.each(function(){if(0!==b(k.tipContent).length){b(k.tipContent).hide();var c=b(k.tipContainer).children("*").first().position(),h=b(k.tipContent+
" li"),f=skipCount=0,g=-1,n,o=function(a,i,e,c){return'<div class="joyride-tip-guide '+a+'" id="joyRidePopup'+i+'"><span class="joyride-nub"></span>'+b(c).html()+e+'<a href="#close" class="joyride-close-tip">&times;</a>'+n+"</div>"},m=function(d,i,e,c){n=0==i&&a.startTimerOnClick&&0<a.timer||0==a.timer?"":'<div class="joyride-timer-indicator-wrap"><span class="joyride-timer-indicator"></span></div>';d||(d="");""!=e?e='<a href="#" class="joyride-next-tip small nice radius yellow button">'+e+"</a>":
e="";a.inline?b(o(d,i,e,c)).insertAfter("#"+b(c).data("id")):b(k.tipContainer).append(o(d,i,e,c))};(!a.cookieMonster||!b.cookie(a.cookieName))&&h.each(function(d){var c=b(this).data("text"),e=b(this).attr("class");a.nextButton&&void 0==c&&(c="Next");a.nextButton||!a.nextButton&&a.startTimerOnClick?b(this).attr("class")?m(e,d,c,this):m(!1,d,c,this):a.nextButton||(b(this).attr("class")?m(e,d,"",this):m(!1,d,"",this));b("#joyRidePopup"+d).hide()});showNextTip=function(){for(var d=b(h[f]).data("id"),
i=b("#"+d);null===i.offset()&&!(f++,skipCount++,h.length-1>g&&g++,d=b(h[f]).data("id"),i=b("#"+d),b(h).length<f););var d=Math.ceil(b(window).height()/2),e=b("#joyRidePopup"+f),l=i.offset(),i=i.outerHeight(),k=e.outerHeight(),j=Math.ceil(b(".joyride-nub").outerHeight()/2),m=0;0!==e.length&&(f<h.length?("pop"==a.tipAnimation?(b(".joyride-timer-indicator").width(0),0<a.timer?e.show().children(".joyride-timer-indicator-wrap").children(".joyride-timer-indicator").animate({width:b(".joyride-timer-indicator-wrap").width()},
a.timer):e.show()):"fade"==a.tipAnimation&&(b(".joyride-timer-indicator").width(0),0<a.timer?e.fadeIn(a.tipAnimationFadeSpeed).children(".joyride-timer-indicator-wrap").children(".joyride-timer-indicator").animate({width:b(".joyride-timer-indicator-wrap").width()},a.timer):e.fadeIn(a.tipAnimationFadeSpeed)),"bottom"==a.tipLocation?(e.offset({top:l.top+i+j,left:l.left-c.left}),e.children(".joyride-nub").addClass("top").removeClass("bottom")):"top"==a.tipLocation&&(k>=l.top?(e.offset({top:l.top+i+j-
c.top,left:l.left-c.left}),e.children(".joyride-nub").addClass("top").removeClass("bottom")):(e.offset({top:l.top-(k+c.top+j),left:l.left-c.left}),e.children(".joyride-nub").addClass("bottom").removeClass("top"))),m=Math.ceil(e.offset().top-d),b("html, body").animate({scrollTop:m},a.scrollSpeed),0<f&&(0<skipCount?(d=g-skipCount,skipCount=0):d=g,"pop"==a.tipAnimation?b("#joyRidePopup"+d).hide():"fade"==a.tipAnimation&&b("#joyRidePopup"+d).fadeOut(a.tipAnimationFadeSpeed))):h.length-1<f&&(0<skipCount?
(d=g-skipCount,skipCount=0):d=g,!0==a.cookieMonster&&b.cookie(a.cookieName,"ridden",{expires:365,domain:a.cookieDomain}),"pop"==a.tipAnimation?b("#joyRidePopup"+d).fadeTo(0,0):"fade"==a.tipAnimation&&b("#joyRidePopup"+d).fadeTo(a.tipAnimationFadeSpeed,0)),f++,0>g?g=0:h.length-1>g&&g++,a.postStepCallback!=b.noop&&a.postStepCallback(g))};(!a.inline||!a.cookieMonster||!b.cookie(a.cookieName))&&b(window).resize(function(){var d=b(h[g]).data("id"),c=b("#"+d).offset(),d=b("#"+d).outerHeight(),e=b("#joyRidePopup"+
g).outerHeight(),f=Math.ceil(b(".joyride-nub").outerHeight()/2);"bottom"==a.tipLocation?b("#joyRidePopup"+g).offset({top:c.top+d+f,left:c.left}):"top"==a.tipLocation&&(c.top<=e?b("#joyRidePopup"+g).offset({top:c.top+f+d,left:c.left}):b("#joyRidePopup"+g).offset({top:c.top-(e+f),left:c.left}))});var j=null;!a.startTimerOnClick&&0<a.timer?(showNextTip(),j=setInterval(function(){showNextTip()},a.timer)):showNextTip();var p=function(c,f,e,g){c.preventDefault();clearInterval(f);e&&b.cookie(a.cookieName,
"ridden",{expires:365,domain:a.cookieDomain});b(g).parent().hide();a.postRideCallback!=b.noop&&a.postRideCallback()};b(".joyride-close-tip").click(function(b){p(b,j,a.cookieMonster,this)});b(".joyride-next-tip").click(function(b){b.preventDefault();f>=h.length&&p(b,j,a.cookieMonster,this);0<a.timer&&a.startTimerOnClick?(showNextTip(),clearInterval(j),j=setInterval(function(){showNextTip()},a.timer)):0<a.timer&&!a.startTimerOnClick?(clearInterval(j),j=setInterval(function(){showNextTip()},a.timer)):
showNextTip()})}})};jQuery.cookie=function(b,a,c){if(1<arguments.length&&"[object Object]"!==""+a){c=jQuery.extend({},c);if(null===a||void 0===a)c.expires=-1;if("number"===typeof c.expires){var h=c.expires,f=c.expires=new Date;f.setDate(f.getDate()+h)}a=""+a;return document.cookie=[encodeURIComponent(b),"=",c.raw?a:encodeURIComponent(a),c.expires?"; expires="+c.expires.toUTCString():"",c.path?"; path="+c.path:"",c.domain?"; domain="+c.domain:"",c.secure?"; secure":""].join("")}c=a||{};f=c.raw?function(a){return a}:
decodeURIComponent;return(h=RegExp("(?:^|; )"+encodeURIComponent(b)+"=([^;]*)").exec(document.cookie))?f(h[1]):null}})(jQuery);